language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7"
- "3.8"
- "3.9"
- "3.10-dev"
- "pypy"
- "pypy3"
# command to install dependencies
install:
  - "python setup.py develop"
  - "pip install pytest"
# command to run tests
script:
  - "python setup.py test"